package com.ds.travel.model;
// Generated Oct 7, 2016 12:53:25 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Integer id;
	private City city;
	private String street;
	private String phone;
	private String postalCode;
	@JsonIgnore private Set profiles = new HashSet(0);

	public Address() {
	}

	public Address(City city, String street, String phone, String postalCode, Set profiles) {
		this.city = city;
		this.street = street;
		this.phone = phone;
		this.postalCode = postalCode;
		this.profiles = profiles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public Set getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set profiles) {
		this.profiles = profiles;
	}

}
