package com.ds.travel.model;
// Generated Oct 7, 2016 12:53:25 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer id;
	private Country country;
	private String name;
	private String district;
	private int population;
	@JsonIgnore private Set stages = new HashSet(0);
	@JsonIgnore private Set addresses = new HashSet(0);

	public City() {
	}

	public City(Country country, String name, String district, int population) {
		this.country = country;
		this.name = name;
		this.district = district;
		this.population = population;
	}

	public City(Country country, String name, String district, int population, Set stages, Set addresses) {
		this.country = country;
		this.name = name;
		this.district = district;
		this.population = population;
		this.stages = stages;
		this.addresses = addresses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public int getPopulation() {
		return this.population;
	}

	public void setPopulation(int population) {
		this.population = population;
	}

	public Set getStages() {
		return this.stages;
	}

	public void setStages(Set stages) {
		this.stages = stages;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

}
