package com.ds.travel.model;
// Generated Oct 7, 2016 12:53:25 PM by Hibernate Tools 5.1.0.Alpha1

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * CountryUser generated by hbm2java
 */
public class CountryUser implements java.io.Serializable {

	private Integer id;
	@JsonIgnore private Country country;
	@JsonIgnore private User user;

	public CountryUser() {
	}

	public CountryUser(Country country, User user) {
		this.country = country;
		this.user = user;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
