package com.ds.travel.model;
// Generated Oct 7, 2016 12:53:25 PM by Hibernate Tools 5.1.0.Alpha1

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Photo generated by hbm2java
 */
public class Photo implements java.io.Serializable {

	private Integer id;
	@JsonIgnore private Travel travel;
	private String name;

	public Photo() {
	}

	public Photo(Travel travel, String name) {
		this.travel = travel;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Travel getTravel() {
		return this.travel;
	}

	public void setTravel(Travel travel) {
		this.travel = travel;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
