package com.ds.travel.model;
// Generated Oct 7, 2016 12:53:25 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private Integer id;
	private Address address;
	private String name;
	private String surname;
	private Date birthday;
	private String avatar;
	private Date createdAt;
	private Date updatedAt;
	private Integer experience;
	@JsonIgnore private Set users = new HashSet(0);

	public Profile() {
	}

	public Profile(Address address, String name, String surname, Date birthday, String avatar, Date createdAt,
			Date updatedAt, Integer experience, Set users) {
		this.address = address;
		this.name = name;
		this.surname = surname;
		this.birthday = birthday;
		this.avatar = avatar;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.experience = experience;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Integer getExperience() {
		return this.experience;
	}

	public void setExperience(Integer experience) {
		this.experience = experience;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
