package com.ds.travel.model;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Stage generated by hbm2java
 */
public class Stage implements java.io.Serializable {

	private Integer id;
	private City city;
	private Travel travel;
	private Date startDate;
	private Date endDate;

	public Stage() {
	}

	public Stage(City city, Travel travel, Date startDate, Date endDate) {
		this.city = city;
		this.travel = travel;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public Travel getTravel() {
		return this.travel;
	}

	public void setTravel(Travel travel) {
		this.travel = travel;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
