package com.ds.travel.model;
// Generated Oct 7, 2016 12:53:25 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Target generated by hbm2java
 */
public class Target implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer miniumBudget;
	private Integer maxiumBudget;
	private String description;
	@JsonIgnore private Set travels = new HashSet(0);

	public Target() {
	}

	public Target(String name, Integer miniumBudget, Integer maxiumBudget, String description, Set travels) {
		this.name = name;
		this.miniumBudget = miniumBudget;
		this.maxiumBudget = maxiumBudget;
		this.description = description;
		this.travels = travels;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getMiniumBudget() {
		return this.miniumBudget;
	}

	public void setMiniumBudget(Integer miniumBudget) {
		this.miniumBudget = miniumBudget;
	}

	public Integer getMaxiumBudget() {
		return this.maxiumBudget;
	}

	public void setMaxiumBudget(Integer maxiumBudget) {
		this.maxiumBudget = maxiumBudget;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTravels() {
		return this.travels;
	}

	public void setTravels(Set travels) {
		this.travels = travels;
	}

}
