package com.ds.travel.model;
// Generated Oct 7, 2016 12:53:25 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Travel generated by hbm2java
 */
public class Travel implements java.io.Serializable {

	private Integer id;
	private Category category;
	private Target target;
	private User user;
	private String title;
	private String description;
	private Integer duration;
	private Integer maxNumberAttendees;
	private Date createdAt;
	private Date updatedAt;
	@JsonIgnore private Set photos = new HashSet(0);
	@JsonIgnore private Set messages = new HashSet(0);
	@JsonIgnore private Set stages = new HashSet(0);
	@JsonIgnore private Set travelTags = new HashSet(0);

	public Travel() {
	}

	public Travel(Category category, Target target, User user, String title, String description, Integer duration,
			Integer maxNumberAttendees, Date createdAt, Date updatedAt, Set photos, Set messages, Set stages,
			Set travelTags) {
		this.category = category;
		this.target = target;
		this.user = user;
		this.title = title;
		this.description = description;
		this.duration = duration;
		this.maxNumberAttendees = maxNumberAttendees;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.photos = photos;
		this.messages = messages;
		this.stages = stages;
		this.travelTags = travelTags;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Target getTarget() {
		return this.target;
	}

	public void setTarget(Target target) {
		this.target = target;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public Integer getMaxNumberAttendees() {
		return this.maxNumberAttendees;
	}

	public void setMaxNumberAttendees(Integer maxNumberAttendees) {
		this.maxNumberAttendees = maxNumberAttendees;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getPhotos() {
		return this.photos;
	}

	public void setPhotos(Set photos) {
		this.photos = photos;
	}

	public Set getMessages() {
		return this.messages;
	}

	public void setMessages(Set messages) {
		this.messages = messages;
	}

	public Set getStages() {
		return this.stages;
	}

	public void setStages(Set stages) {
		this.stages = stages;
	}

	public Set getTravelTags() {
		return this.travelTags;
	}

	public void setTravelTags(Set travelTags) {
		this.travelTags = travelTags;
	}

}
